fix: switch example to pnpm to fix permissions bug
Using the "Deploy to Netlify" link for the `astro-server-islands` site
fails at the initializing build step with this error:
```
Error: EACCES: permission denied, open
'/opt/build/repo/package-lock.json'
```

I don't know what's causing this, but switching to pnpm fixes it, so
let's just merge this for now.

FRP-1217